### ISSUE TITLE
maximize uses wrong default value if constraints are violated

### ISSUE THREAD

**Issue by rene-rex** [claesenm/optunity#35]
In optunity/api.py line 176 sys.float_info.min is set as default:

> f = _wrap_hard_box_constraints(f, kwargs, sys.float_info.min)

However, sys.float_info.min is the "minimum positive normalized float" [1] which evaluates to 2.2250738585072014e-308 in my case. This causes maximize to to choose parameters that violate constraints if something like a negative mean squared error should be maximized. I suggest to replace this line by:
> f = _wrap_hard_box_constraints(f, kwargs, -sys.float_info.max)

[1] https://docs.python.org/2/library/sys.html#sys.float_info

**Comment by claesenm** [comment]
Thanks for identifying this problem. Your suggestion indeed fixes the problem, I will make the modification.
