### ISSUE TITLE
Better example for CV

### ISSUE THREAD

**Issue by jaak-s** [claesenm/optunity#36]
In the doc the first CV example returns 0.0. Maybe we could have a more practical example there?
http://optunity.readthedocs.org/en/latest/user/cross_validation.html

```python
@opt.cross_validated(x=data, y=labels, num_folds=3)
def cved(x_train, y_train, x_test, y_test):
    train(x_train, y_train)
    predict(x_test)
    return 0.0

cved()
```

**Comment by claesenm** [comment]
Yeah sure. I made that one to show what the code typically looks like, but
it's not the bestest example for sure.

2015-02-03 9:58 GMT+01:00 Jaak Simm <notifications@github.com>:

**Comment by jaak-s** [comment]
Yeah, maybe not too crucial as there is a nice CV example in the main doc page. Feel free to close this issue.

**Comment by claesenm** [comment]
Nah, I'll leave it open so I won't forget to improve it eventually. Won't
be in the next few days though ...

2015-02-03 10:27 GMT+01:00 Jaak Simm <notifications@github.com>:

**Comment by claesenm** [comment]
A full notebook is available on cross-validation now at http://optunity.readthedocs.org/en/latest/notebooks/notebooks/basic-cross-validation.html
