### ISSUE TITLE
handling of discrete hyperparameters

### ISSUE THREAD

**Issue by updiversity** [claesenm/optunity#41]
Hi,

I'd like to know if it is possible to use optunity to find hyperparameter solutions, when these parameters are discrete.

Then is it possible with non-ordinal hyperparameters ?

Finally, if it is not possible, do you plan to implement it and in case the answer is affirmative, for when ?

**Comment by claesenm** [comment]
For discrete parameters we currently recommend rounding the values yielded by Optunity. Dealing with non-ordinal hyperparameters is currently not possible, but it is part of our future planning. Unfortunately I cannot specify a timeline on that specific feature at this point.

**Comment by claesenm** [comment]
In a few days we will add functionality to work with conditional hyperparameters. This functionality will also be applicable for non-ordinal hyperparameters.

**Comment by claesenm** [comment]
Dealing with hyperparameters conditional upon some discrete choice is now fully integrated, e.g. http://optunity.readthedocs.org/en/latest/notebooks/notebooks/sklearn-svc.html#tune-svc-without-deciding-the-kernel-in-advance
