### ISSUE TITLE
Optimize class weights

### ISSUE THREAD

**Issue by rmurray2** [claesenm/optunity#42]
Is it possible to tune a classifier's class weight vector using optunity?

Currently the parameter space is defined in optunity's 'minimize' and 'maximize' by passing it the lower and upper bounds. This assumes the parameter is a single number (such as 'C' or 'gamma'). I am wondering whether it is possible to optimize a weight vector, for example, where the length of the vector equals the number of classes. 

Thanks

**Comment by claesenm** [comment]
This is currently not supported directly, however you could obtain the same effect by creating an appropriate amount of variables, e.g. w1, w2, ... wN where N equals the number of classes.

This is a little cumbersome, but it will give you the same effect.
