### ISSUE TITLE
suggest() got multiple values for keyword argument 'seed'

### ISSUE THREAD

**Issue by chrinide** [claesenm/optunity#44]
If Use 'TPE' solver, the code will return below error:

optunity\solvers\TPE.pyc in algo(*args, **kwargs)
    117         def algo(*args, **kwargs):
    118             seed = self.seed if self.seed else random.randint(0, 9999999999)
--> 119             return hyperopt.tpe.suggest(*args, seed=seed **kwargs)
    120 
    121         space = [hyperopt.hp.uniform(k, v[0], v[1]) for k, v in self.bounds.items()]

TypeError: suggest() got multiple values for keyword argument 'seed'

**Comment by claesenm** [comment]
Thanks for reporting this issue, I will check it out in the next few days.

**Comment by aminevsaziz** [comment]
Hey @claesenm the issue still exist with tpe for some reason
here is the log:
`--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
 in 
     94 
     95 
---> 96 auc = nested_cv()
     97 print('')
     98 print('Nested AUROC: %1.3f' % auc)

~/miniconda3/lib/python3.7/site-packages/optunity/cross_validation.py in __call__(self, *args, **kwargs)
    401                     kwargs['y_train'] = select(self.y, rows_train)
    402                     kwargs['y_test'] = select(self.y, rows_test)
--> 403                 scores.append(self.f(**kwargs))
    404         return self.reduce(scores)
    405 

 in nested_cv(x_train, y_train, x_test, y_test)
     85 
     86     hpars, info, _ = optunity.minimize(inner_cv, num_evals=10,
---> 87                                     C=[0, 10], logGamma=[-5, 1],solver_name="tpe")
     88     print('')
     89     print('Hyperparameters: ' + str(hpars))

~/miniconda3/lib/python3.7/site-packages/optunity/api.py in minimize(f, num_evals, solver_name, pmap, **kwargs)
    210     solver = make_solver(**suggestion)
    211     solution, details = optimize(solver, func, maximize=False, max_evals=num_evals,
--> 212                                  pmap=pmap)
    213     return solution, details, suggestion
    214 

~/miniconda3/lib/python3.7/site-packages/optunity/api.py in optimize(solver, func, maximize, max_evals, pmap, decoder)
    243     time = timeit.default_timer()
    244     try:
--> 245         solution, report = solver.optimize(f, maximize, pmap=pmap)
    246     except fun.MaximumEvaluationsException:
    247         # early stopping because maximum number of evaluations is reached

~/miniconda3/lib/python3.7/site-packages/optunity/solvers/TPE.py in optimize(self, f, maximize, pmap)
    127 
    128         space = [hyperopt.hp.uniform(k, v[0], v[1]) for k, v in self.bounds.items()]
--> 129         best = hyperopt.fmin(obj, space=space, algo=algo, max_evals=self.num_evals)
    130         return best, None
    131 

~/miniconda3/lib/python3.7/site-packages/hyperopt/fmin.py in fmin(fn, space, algo, max_evals, trials, rstate, allow_trials_fmin, pass_expr_memo_ctrl, catch_eval_exceptions, verbose, return_argmin, points_to_evaluate, max_queue_len, show_progressbar)
    405                     show_progressbar=show_progressbar)
    406     rval.catch_eval_exceptions = catch_eval_exceptions
--> 407     rval.exhaust()
    408     if return_argmin:
    409         return trials.argmin

~/miniconda3/lib/python3.7/site-packages/hyperopt/fmin.py in exhaust(self)
    260     def exhaust(self):
    261         n_done = len(self.trials)
--> 262         self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
    263         self.trials.refresh()
    264         return self

~/miniconda3/lib/python3.7/site-packages/hyperopt/fmin.py in run(self, N, block_until_done)
    209                                                           d['result'].get('status')))
    210                         new_trials = algo(new_ids, self.domain, trials,
--> 211                                           self.rstate.randint(2 ** 31 - 1))
    212                         assert len(new_ids) >= len(new_trials)
    213                         if len(new_trials):

TypeError: suggest() got multiple values for argument 'seed'`

any suggestion on how to solve such issue?

**Comment by antmontieri** [comment]
The problem is that the instruction `algo = functools.partial(hyperopt.tpe.suggest, seed=seed)` is trying to set the keyword argument `seed` already set by hyperopt as a positional argument.

I have solved substituting  `algo = functools.partial(hyperopt.tpe.suggest, seed=seed)` 
with  `algo = hyperopt.tpe.suggest`.
