### ISSUE TITLE
Patch to handle cross-validation when X is a sparse matrix

### ISSUE THREAD

**Issue by FedericoV** [claesenm/optunity#69]
Hi,

Thanks for the awesome package.  Optunity, by default, does not handle the case when X is sparse, since it tries to figure out the shape of X by calling len(X).

I added a small patch where I changed calls to len(X) with X.shape[0] which is valid even in the case where X is a scipy sparse matrix.

**Comment by FedericoV** [comment]
From 1a49c9f965d5397471bc8105c73236e8af5edf1e Mon Sep 17 00:00:00 2001
From: Federico Vaggi <vaggi.federico@gmail.com>
Date: Wed, 24 Feb 2016 09:48:56 +0100
Subject: [PATCH] Changed len(x) to X.shape[0] handle case where X is a sparse
 matrix

---
 optunity/cross_validation.py |   10 +++++++---
 1 file changed, 7 insertions(+), 3 deletions(-)

diff --git a/optunity/cross_validation.py b/optunity/cross_validation.py
index f94743e..beb9a13 100755
--- a/optunity/cross_validation.py
+++ b/optunity/cross_validation.py
@@ -234,7 +234,8 @@ def generate_folds(num_rows, num_folds=10, strata=None, clusters=None):
     return folds
 
 def mean(x):
-    return float(sum(x)) / len(x)
+    x_len = len(x)
+    return float(sum(x)) / x_len
 
 def mean_and_list(x):
     """Returns a tuple, the first element is the mean of x and the second is x itself.
@@ -477,9 +478,12 @@ def cross_validated(x, num_folds=10, y=None, strata=None, folds=None, num_iter=1
     AssertionError
 
     """
-    assert(num_folds <= len(x))
-    assert(y is None or len(y) == len(x))
+    x_len = x.shape[0]
+
+    assert(num_folds <= x_len)
+    assert(y is None or len(y) == x_len)
     args = dict(locals())
+    args.pop('x_len', None)
     def wrapper(f):
         args['f'] = f
         return cross_validated_callable(**args)
-- 
1.7.10.4

**Comment by claesenm** [comment]
Thanks, I will check it out in the next few days!

2016-02-24 9:50 GMT+01:00 Federico Vaggi <notifications@github.com>:

**Comment by claesenm** [comment]
Thanks for your suggested fix. I've incorporated this with some minor changes in master.
